# app-deployment.yaml - Deployment de la aplicación Flask con ConfigMap y Secret
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web-deployment
  labels:
    app: app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - name: app-web
        image: mi-app-web:v1
        imagePullPolicy: Never  # Para usar imagen local de Minikube
        ports:
        - containerPort: 5000
        env:
        # Variables desde ConfigMap
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        # Variable sensible desde Secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-service
spec:
  selector:
    app: app-web
  ports:
    - protocol: TCP
      port: 8080 # Puerto que el Service expone
      targetPort: 5000 # Puerto del contenedor (Flask)
  type: NodePort # Para acceder desde tu máquina